apiVersion: v1
kind: Pod
metadata:
  name: config-map-pod
  namespace: dev
spec:
  containers:
    - name: nginx-container
      image: nginx:1.19.6
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: name
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: password
      envFrom:
        - configMapRef:
            name: literal-config
